/* 
 * CryptoWeather
 *
 * The CryptoWeather API allows for access to all of the cryptocurrency data and market forecast services provided. There are two primary categories of routes, `public` and `private`, where `public` routes are accessible to the general public and do not require API authentication, and `private` routes, which require API authentication.  ## General Overview  1. All API methods adhere to RESTful best practices as closely as possible. As such, all API calls will be made via the standard HTTP protocol using the GET/POST/PUT/DELETE request types.  2. Every request returns the status as a JSON response with the following:     - success, true if it was successful     - code, the http status code (also in the response header)         - 200 if response is successful         - 400 if bad request         - 401 if authorization JWT is wrong or limit exceeded         - 404 wrong route         - 500 for any internal errors     - status, the status of the request, default **success**     - errors, an array of any relevant error details  3. For any requests that are not successful an error message is specified and returned as an array for the **errors** key in the JSON response.  4. All authentication uses JSON Web Tokens (JWT), which is set as the **Authorization** entry in the header, see the following for more details.     - http://jwt.io     - https://scotch.io/tutorials/the-anatomy-of-a-json-web-token  ## Code Example  The following is a code example in Python, which demonstrates using the [Python Requests library](https://requests.readthedocs.io/en/master/) for both the `public` and `private` API routes.  ``` import requests  HOST = \"https://api.cryptoweather.ai/v1\"  # Your API key (JWT) API_KEY = \"<YOUR API KEY>\"  # Example public request, no API key required. requests.get(\"{}/public/symbols\".format(HOST)).json()  # Get the current btc price using the public route requests.get(\"{}/public/price-current/{}\".format(HOST, \"btc\")).json()   # Example private request, API key required. Get the btc hourly forecasts headers = {\"Authorization\": \"Bearer {}\".format(API_KEY)} requests.get(\"{}/private/forecast/{}/{}\".format(HOST, \"btc\", \"1h\"),              headers=headers).json() ```
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PrivateApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PrivateApiTests
    {
        private PrivateApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PrivateApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PrivateApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PrivateApi
            //Assert.IsInstanceOfType(typeof(PrivateApi), instance, "instance is a PrivateApi");
        }

        
        /// <summary>
        /// Test V1PrivateAccuracySymbolIntervalPeriodGet
        /// </summary>
        [Test]
        public void V1PrivateAccuracySymbolIntervalPeriodGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string symbol = null;
            //string interval = null;
            //string period = null;
            //string cookie = null;
            //string xCsrf = null;
            //var response = instance.V1PrivateAccuracySymbolIntervalPeriodGet(symbol, interval, period, cookie, xCsrf);
            //Assert.IsInstanceOf<PrivateAccuracyResponse> (response, "response is PrivateAccuracyResponse");
        }
        
        /// <summary>
        /// Test V1PrivateForecastSymbolIntervalGet
        /// </summary>
        [Test]
        public void V1PrivateForecastSymbolIntervalGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string symbol = null;
            //string interval = null;
            //string cookie = null;
            //string xCsrf = null;
            //var response = instance.V1PrivateForecastSymbolIntervalGet(symbol, interval, cookie, xCsrf);
            //Assert.IsInstanceOf<PrivateForecastResponse> (response, "response is PrivateForecastResponse");
        }
        
        /// <summary>
        /// Test V1PrivateTrendSymbolGet
        /// </summary>
        [Test]
        public void V1PrivateTrendSymbolGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string symbol = null;
            //string cookie = null;
            //string xCsrf = null;
            //var response = instance.V1PrivateTrendSymbolGet(symbol, cookie, xCsrf);
            //Assert.IsInstanceOf<PublicTrendResponse> (response, "response is PublicTrendResponse");
        }
        
        /// <summary>
        /// Test V1PrivateTrendTabularGet
        /// </summary>
        [Test]
        public void V1PrivateTrendTabularGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string cookie = null;
            //string xCsrf = null;
            //var response = instance.V1PrivateTrendTabularGet(cookie, xCsrf);
            //Assert.IsInstanceOf<PrivateTrendTabularResponse> (response, "response is PrivateTrendTabularResponse");
        }
        
    }

}
