/* 
 * CryptoWeather
 *
 * The CryptoWeather API allows for access to all of the cryptocurrency data and market forecast services provided. There are two primary categories of routes, `public` and `private`, where `public` routes are accessible to the general public and do not require API authentication, and `private` routes, which require API authentication.  ## General Overview  1. All API methods adhere to RESTful best practices as closely as possible. As such, all API calls will be made via the standard HTTP protocol using the GET/POST/PUT/DELETE request types.  2. Every request returns the status as a JSON response with the following:     - success, true if it was successful     - code, the http status code (also in the response header)         - 200 if response is successful         - 400 if bad request         - 401 if authorization JWT is wrong or limit exceeded         - 404 wrong route         - 500 for any internal errors     - status, the status of the request, default **success**     - errors, an array of any relevant error details  3. For any requests that are not successful an error message is specified and returned as an array for the **errors** key in the JSON response.  4. All authentication uses JSON Web Tokens (JWT), which is set as the **Authorization** entry in the header, see the following for more details.     - http://jwt.io     - https://scotch.io/tutorials/the-anatomy-of-a-json-web-token  ## Code Example  The following is a code example in Python, which demonstrates using the [Python Requests library](https://requests.readthedocs.io/en/master/) for both the `public` and `private` API routes.  ``` import requests  HOST = \"https://api.cryptoweather.ai/v1\"  # Your API key (JWT) API_KEY = \"<YOUR API KEY>\"  # Example public request, no API key required. requests.get(\"{}/public/symbols\".format(HOST)).json()  # Get the current btc price using the public route requests.get(\"{}/public/price-current/{}\".format(HOST, \"btc\")).json()   # Example private request, API key required. Get the btc hourly forecasts headers = {\"Authorization\": \"Bearer {}\".format(API_KEY)} requests.get(\"{}/private/forecast/{}/{}\".format(HOST, \"btc\", \"1h\"),              headers=headers).json() ```
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PublicPriceCurrentResponseDataCurrent
    /// </summary>
    [DataContract]
    public partial class PublicPriceCurrentResponseDataCurrent :  IEquatable<PublicPriceCurrentResponseDataCurrent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicPriceCurrentResponseDataCurrent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PublicPriceCurrentResponseDataCurrent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicPriceCurrentResponseDataCurrent" /> class.
        /// </summary>
        /// <param name="symbol">symbol (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="price">price (required).</param>
        /// <param name="changeUsd">changeUsd (required).</param>
        /// <param name="changePct">changePct (required).</param>
        public PublicPriceCurrentResponseDataCurrent(string symbol = default(string), string name = default(string), decimal? price = default(decimal?), decimal? changeUsd = default(decimal?), decimal? changePct = default(decimal?))
        {
            // to ensure "symbol" is required (not null)
            if (symbol == null)
            {
                throw new InvalidDataException("symbol is a required property for PublicPriceCurrentResponseDataCurrent and cannot be null");
            }
            else
            {
                this.Symbol = symbol;
            }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for PublicPriceCurrentResponseDataCurrent and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "price" is required (not null)
            if (price == null)
            {
                throw new InvalidDataException("price is a required property for PublicPriceCurrentResponseDataCurrent and cannot be null");
            }
            else
            {
                this.Price = price;
            }
            // to ensure "changeUsd" is required (not null)
            if (changeUsd == null)
            {
                throw new InvalidDataException("changeUsd is a required property for PublicPriceCurrentResponseDataCurrent and cannot be null");
            }
            else
            {
                this.ChangeUsd = changeUsd;
            }
            // to ensure "changePct" is required (not null)
            if (changePct == null)
            {
                throw new InvalidDataException("changePct is a required property for PublicPriceCurrentResponseDataCurrent and cannot be null");
            }
            else
            {
                this.ChangePct = changePct;
            }
        }
        
        /// <summary>
        /// Gets or Sets Symbol
        /// </summary>
        [DataMember(Name="symbol", EmitDefaultValue=false)]
        public string Symbol { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name="price", EmitDefaultValue=false)]
        public decimal? Price { get; set; }

        /// <summary>
        /// Gets or Sets ChangeUsd
        /// </summary>
        [DataMember(Name="change_usd", EmitDefaultValue=false)]
        public decimal? ChangeUsd { get; set; }

        /// <summary>
        /// Gets or Sets ChangePct
        /// </summary>
        [DataMember(Name="change_pct", EmitDefaultValue=false)]
        public decimal? ChangePct { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PublicPriceCurrentResponseDataCurrent {\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  ChangeUsd: ").Append(ChangeUsd).Append("\n");
            sb.Append("  ChangePct: ").Append(ChangePct).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PublicPriceCurrentResponseDataCurrent);
        }

        /// <summary>
        /// Returns true if PublicPriceCurrentResponseDataCurrent instances are equal
        /// </summary>
        /// <param name="input">Instance of PublicPriceCurrentResponseDataCurrent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PublicPriceCurrentResponseDataCurrent input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Symbol == input.Symbol ||
                    (this.Symbol != null &&
                    this.Symbol.Equals(input.Symbol))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Price == input.Price ||
                    (this.Price != null &&
                    this.Price.Equals(input.Price))
                ) && 
                (
                    this.ChangeUsd == input.ChangeUsd ||
                    (this.ChangeUsd != null &&
                    this.ChangeUsd.Equals(input.ChangeUsd))
                ) && 
                (
                    this.ChangePct == input.ChangePct ||
                    (this.ChangePct != null &&
                    this.ChangePct.Equals(input.ChangePct))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Symbol != null)
                    hashCode = hashCode * 59 + this.Symbol.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Price != null)
                    hashCode = hashCode * 59 + this.Price.GetHashCode();
                if (this.ChangeUsd != null)
                    hashCode = hashCode * 59 + this.ChangeUsd.GetHashCode();
                if (this.ChangePct != null)
                    hashCode = hashCode * 59 + this.ChangePct.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
