/* 
 * CryptoWeather
 *
 * The CryptoWeather API allows for access to all of the cryptocurrency data and market forecast services provided. There are two primary categories of routes, `public` and `private`, where `public` routes are accessible to the general public and do not require API authentication, and `private` routes, which require API authentication.  ## General Overview  1. All API methods adhere to RESTful best practices as closely as possible. As such, all API calls will be made via the standard HTTP protocol using the GET/POST/PUT/DELETE request types.  2. Every request returns the status as a JSON response with the following:     - success, true if it was successful     - code, the http status code (also in the response header)         - 200 if response is successful         - 400 if bad request         - 401 if authorization JWT is wrong or limit exceeded         - 404 wrong route         - 500 for any internal errors     - status, the status of the request, default **success**     - errors, an array of any relevant error details  3. For any requests that are not successful an error message is specified and returned as an array for the **errors** key in the JSON response.  4. All authentication uses JSON Web Tokens (JWT), which is set as the **Authorization** entry in the header, see the following for more details.     - http://jwt.io     - https://scotch.io/tutorials/the-anatomy-of-a-json-web-token  ## Code Example  The following is a code example in Python, which demonstrates using the [Python Requests library](https://requests.readthedocs.io/en/master/) for both the `public` and `private` API routes.  ``` import requests  HOST = \"https://api.cryptoweather.ai/v1\"  # Your API key (JWT) API_KEY = \"<YOUR API KEY>\"  # Example public request, no API key required. requests.get(\"{}/public/symbols\".format(HOST)).json()  # Get the current btc price using the public route requests.get(\"{}/public/price-current/{}\".format(HOST, \"btc\")).json()   # Example private request, API key required. Get the btc hourly forecasts headers = {\"Authorization\": \"Bearer {}\".format(API_KEY)} requests.get(\"{}/private/forecast/{}/{}\".format(HOST, \"btc\", \"1h\"),              headers=headers).json() ```
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PublicTrendResponseDataTrend
    /// </summary>
    [DataContract]
    public partial class PublicTrendResponseDataTrend :  IEquatable<PublicTrendResponseDataTrend>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicTrendResponseDataTrend" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PublicTrendResponseDataTrend() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicTrendResponseDataTrend" /> class.
        /// </summary>
        /// <param name="timeStart">timeStart (required).</param>
        /// <param name="timeEnd">timeEnd (required).</param>
        /// <param name="interval">interval (required).</param>
        /// <param name="weightedPrice">weightedPrice (required).</param>
        /// <param name="changeUsd">changeUsd (required).</param>
        /// <param name="changePct">changePct (required).</param>
        /// <param name="confidence">confidence (required).</param>
        public PublicTrendResponseDataTrend(decimal? timeStart = default(decimal?), decimal? timeEnd = default(decimal?), string interval = default(string), decimal? weightedPrice = default(decimal?), decimal? changeUsd = default(decimal?), decimal? changePct = default(decimal?), decimal? confidence = default(decimal?))
        {
            // to ensure "timeStart" is required (not null)
            if (timeStart == null)
            {
                throw new InvalidDataException("timeStart is a required property for PublicTrendResponseDataTrend and cannot be null");
            }
            else
            {
                this.TimeStart = timeStart;
            }
            // to ensure "timeEnd" is required (not null)
            if (timeEnd == null)
            {
                throw new InvalidDataException("timeEnd is a required property for PublicTrendResponseDataTrend and cannot be null");
            }
            else
            {
                this.TimeEnd = timeEnd;
            }
            // to ensure "interval" is required (not null)
            if (interval == null)
            {
                throw new InvalidDataException("interval is a required property for PublicTrendResponseDataTrend and cannot be null");
            }
            else
            {
                this.Interval = interval;
            }
            // to ensure "weightedPrice" is required (not null)
            if (weightedPrice == null)
            {
                throw new InvalidDataException("weightedPrice is a required property for PublicTrendResponseDataTrend and cannot be null");
            }
            else
            {
                this.WeightedPrice = weightedPrice;
            }
            // to ensure "changeUsd" is required (not null)
            if (changeUsd == null)
            {
                throw new InvalidDataException("changeUsd is a required property for PublicTrendResponseDataTrend and cannot be null");
            }
            else
            {
                this.ChangeUsd = changeUsd;
            }
            // to ensure "changePct" is required (not null)
            if (changePct == null)
            {
                throw new InvalidDataException("changePct is a required property for PublicTrendResponseDataTrend and cannot be null");
            }
            else
            {
                this.ChangePct = changePct;
            }
            // to ensure "confidence" is required (not null)
            if (confidence == null)
            {
                throw new InvalidDataException("confidence is a required property for PublicTrendResponseDataTrend and cannot be null");
            }
            else
            {
                this.Confidence = confidence;
            }
        }
        
        /// <summary>
        /// Gets or Sets TimeStart
        /// </summary>
        [DataMember(Name="time_start", EmitDefaultValue=false)]
        public decimal? TimeStart { get; set; }

        /// <summary>
        /// Gets or Sets TimeEnd
        /// </summary>
        [DataMember(Name="time_end", EmitDefaultValue=false)]
        public decimal? TimeEnd { get; set; }

        /// <summary>
        /// Gets or Sets Interval
        /// </summary>
        [DataMember(Name="interval", EmitDefaultValue=false)]
        public string Interval { get; set; }

        /// <summary>
        /// Gets or Sets WeightedPrice
        /// </summary>
        [DataMember(Name="weighted_price", EmitDefaultValue=false)]
        public decimal? WeightedPrice { get; set; }

        /// <summary>
        /// Gets or Sets ChangeUsd
        /// </summary>
        [DataMember(Name="change_usd", EmitDefaultValue=false)]
        public decimal? ChangeUsd { get; set; }

        /// <summary>
        /// Gets or Sets ChangePct
        /// </summary>
        [DataMember(Name="change_pct", EmitDefaultValue=false)]
        public decimal? ChangePct { get; set; }

        /// <summary>
        /// Gets or Sets Confidence
        /// </summary>
        [DataMember(Name="confidence", EmitDefaultValue=false)]
        public decimal? Confidence { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PublicTrendResponseDataTrend {\n");
            sb.Append("  TimeStart: ").Append(TimeStart).Append("\n");
            sb.Append("  TimeEnd: ").Append(TimeEnd).Append("\n");
            sb.Append("  Interval: ").Append(Interval).Append("\n");
            sb.Append("  WeightedPrice: ").Append(WeightedPrice).Append("\n");
            sb.Append("  ChangeUsd: ").Append(ChangeUsd).Append("\n");
            sb.Append("  ChangePct: ").Append(ChangePct).Append("\n");
            sb.Append("  Confidence: ").Append(Confidence).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PublicTrendResponseDataTrend);
        }

        /// <summary>
        /// Returns true if PublicTrendResponseDataTrend instances are equal
        /// </summary>
        /// <param name="input">Instance of PublicTrendResponseDataTrend to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PublicTrendResponseDataTrend input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TimeStart == input.TimeStart ||
                    (this.TimeStart != null &&
                    this.TimeStart.Equals(input.TimeStart))
                ) && 
                (
                    this.TimeEnd == input.TimeEnd ||
                    (this.TimeEnd != null &&
                    this.TimeEnd.Equals(input.TimeEnd))
                ) && 
                (
                    this.Interval == input.Interval ||
                    (this.Interval != null &&
                    this.Interval.Equals(input.Interval))
                ) && 
                (
                    this.WeightedPrice == input.WeightedPrice ||
                    (this.WeightedPrice != null &&
                    this.WeightedPrice.Equals(input.WeightedPrice))
                ) && 
                (
                    this.ChangeUsd == input.ChangeUsd ||
                    (this.ChangeUsd != null &&
                    this.ChangeUsd.Equals(input.ChangeUsd))
                ) && 
                (
                    this.ChangePct == input.ChangePct ||
                    (this.ChangePct != null &&
                    this.ChangePct.Equals(input.ChangePct))
                ) && 
                (
                    this.Confidence == input.Confidence ||
                    (this.Confidence != null &&
                    this.Confidence.Equals(input.Confidence))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TimeStart != null)
                    hashCode = hashCode * 59 + this.TimeStart.GetHashCode();
                if (this.TimeEnd != null)
                    hashCode = hashCode * 59 + this.TimeEnd.GetHashCode();
                if (this.Interval != null)
                    hashCode = hashCode * 59 + this.Interval.GetHashCode();
                if (this.WeightedPrice != null)
                    hashCode = hashCode * 59 + this.WeightedPrice.GetHashCode();
                if (this.ChangeUsd != null)
                    hashCode = hashCode * 59 + this.ChangeUsd.GetHashCode();
                if (this.ChangePct != null)
                    hashCode = hashCode * 59 + this.ChangePct.GetHashCode();
                if (this.Confidence != null)
                    hashCode = hashCode * 59 + this.Confidence.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
